package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.dao.GameDaoSQLImpl;
import ba.unsa.etf.rpr.domain.Game;
import ba.unsa.etf.rpr.exceptions.TicketException;
import org.apache.commons.lang.RandomStringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

public class GameManagerTest {

    private GameManager gameManager;
    private Game game;
    private GameDaoSQLImpl gameDaoSQLMock;
    private List<Game> games;

    private Game createGame(int id, int capacity, int sold, String competition, String opponent){
        Game game = new Game();
        game.setId(id);
        game.setCapacity(capacity);
        game.setSold(sold);
        game.setDate(LocalDate.now());
        game.setCompetition(competition);
        game.setOpponent(opponent);
        return game;
    }

    /**
     * This method is called before each test
     */
    @BeforeEach
    public void initializeObjectsWeNeed(){
        gameManager = Mockito.mock(GameManager.class);
        game = new Game();
        game.setId(50);
        game.setCapacity(12056);
        game.setSold(0);
        LocalDate date = LocalDate.now();
        game.setDate(date);
        game.setCompetition("Premijer Liga BiH");
        game.setOpponent("Fk Velež Mostar");

        gameDaoSQLMock = Mockito.mock(GameDaoSQLImpl.class);
        games = new ArrayList<>();
        games.add(createGame(51, 5000, 5, "Kup BiH", "Fk Tuzla City"));
        games.add(createGame(52, 6000, 20, "Liga Prvaka", "Manchester City"));
        games.add(createGame(53, 12056, 1000, "Premijer Liga BiH", "Nk Široki Brijeg"));
    }

    @Test
    void validateCompetitionNameCorrect() throws TicketException{
        String correctName = "Kup BiH";
        try {
            Mockito.doCallRealMethod().when(gameManager).validateCompetitionName(correctName);
        } catch (TicketException e){
            e.printStackTrace();
            Assertions.assertTrue(false);
        }
    }

    @Test
    void validateCompetitionNameShort() throws TicketException{
        String incorrectNameShort = "A";  //must be at least three characters
        Mockito.doCallRealMethod().when(gameManager).validateCompetitionName(incorrectNameShort);
        TicketException ticketException1 = Assertions.assertThrows(TicketException.class, () -> {
            gameManager.validateCompetitionName(incorrectNameShort);}, "Competition name must be between 3 and 45 characters");
        Assertions.assertEquals("Competition name must be between 3 and 45 characters", ticketException1.getMessage());
    }

    @Test
    void validateCompetitionNameLong() throws TicketException{
        String incorrectNameLong = RandomStringUtils.randomAlphabetic(50);
        Mockito.doCallRealMethod().when(gameManager).validateCompetitionName(incorrectNameLong);
        TicketException ticketException2 = Assertions.assertThrows(TicketException.class, () -> {
            gameManager.validateCompetitionName(incorrectNameLong);}, "Competition name must be between 3 and 45 characters");
        Assertions.assertEquals("Competition name must be between 3 and 45 characters", ticketException2.getMessage());
    }

    @Test
    void add() throws TicketException {
        MockedStatic<DaoFactory> daoFactoryMockedStatic = Mockito.mockStatic(DaoFactory.class);
        daoFactoryMockedStatic.when(DaoFactory::gameDao).thenReturn(gameDaoSQLMock);
        /*
        An exception will be thrown because our instance of Category.java class has value for id
         */
        when(DaoFactory.gameDao().getAll()).thenReturn(games);
        Mockito.doCallRealMethod().when(gameManager).add(game);
        TicketException quoteException = Assertions.assertThrows(TicketException.class, () -> {
            gameManager.add(game);}, "Can't add category with ID. ID is autogenerated");

        Assertions.assertEquals("Can't add category with ID. ID is autogenerated", quoteException.getMessage());
        daoFactoryMockedStatic.verify(DaoFactory::gameDao);
        Mockito.verify(gameManager).add(game);
        daoFactoryMockedStatic.close();
    }

    @Test
    void addNewGame() throws TicketException {
        Game newGame = createGame(60, 5050, 1700, "Premijer Liga BiH", "Fk Borac Banja Luka");
        gameManager.add(newGame);
        Assertions.assertTrue(true);
        Mockito.verify(gameManager).add(newGame);
    }

    @Test
    void deleteGame() throws TicketException{
        gameManager.delete(50);
        Assertions.assertTrue(true);
        Mockito.verify(gameManager).delete(50);
    }

}
